#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportShop_Project.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SportShopDB")]
	public partial class SportShopDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertShoe(Shoe instance);
    partial void UpdateShoe(Shoe instance);
    partial void DeleteShoe(Shoe instance);
    partial void InsertSportClub(SportClub instance);
    partial void UpdateSportClub(SportClub instance);
    partial void DeleteSportClub(SportClub instance);
    partial void InsertCloth(Cloth instance);
    partial void UpdateCloth(Cloth instance);
    partial void DeleteCloth(Cloth instance);
    partial void InsertSportEquipment(SportEquipment instance);
    partial void UpdateSportEquipment(SportEquipment instance);
    partial void DeleteSportEquipment(SportEquipment instance);
    #endregion
		
		public SportShopDBDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["SportShopDBConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public SportShopDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SportShopDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SportShopDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SportShopDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Shoe> Shoes
		{
			get
			{
				return this.GetTable<Shoe>();
			}
		}
		
		public System.Data.Linq.Table<SportClub> SportClubs
		{
			get
			{
				return this.GetTable<SportClub>();
			}
		}
		
		public System.Data.Linq.Table<Cloth> Cloths
		{
			get
			{
				return this.GetTable<Cloth>();
			}
		}
		
		public System.Data.Linq.Table<SportEquipment> SportEquipments
		{
			get
			{
				return this.GetTable<SportEquipment>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Shoes")]
	public partial class Shoe : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _ShoeType;
		
		private string _ShoeBrand;
		
		private string _ShoeModel;
		
		private System.Nullable<int> _ShoePrice;
		
		private System.Nullable<int> _ShoeQuentity;
		
		private System.Nullable<bool> _ShoeInSale;
		
		private string _ShoePicture;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnShoeTypeChanging(string value);
    partial void OnShoeTypeChanged();
    partial void OnShoeBrandChanging(string value);
    partial void OnShoeBrandChanged();
    partial void OnShoeModelChanging(string value);
    partial void OnShoeModelChanged();
    partial void OnShoePriceChanging(System.Nullable<int> value);
    partial void OnShoePriceChanged();
    partial void OnShoeQuentityChanging(System.Nullable<int> value);
    partial void OnShoeQuentityChanged();
    partial void OnShoeInSaleChanging(System.Nullable<bool> value);
    partial void OnShoeInSaleChanged();
    partial void OnShoePictureChanging(string value);
    partial void OnShoePictureChanged();
    #endregion
		
		public Shoe()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShoeType", DbType="NVarChar(50)")]
		public string ShoeType
		{
			get
			{
				return this._ShoeType;
			}
			set
			{
				if ((this._ShoeType != value))
				{
					this.OnShoeTypeChanging(value);
					this.SendPropertyChanging();
					this._ShoeType = value;
					this.SendPropertyChanged("ShoeType");
					this.OnShoeTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShoeBrand", DbType="NVarChar(50)")]
		public string ShoeBrand
		{
			get
			{
				return this._ShoeBrand;
			}
			set
			{
				if ((this._ShoeBrand != value))
				{
					this.OnShoeBrandChanging(value);
					this.SendPropertyChanging();
					this._ShoeBrand = value;
					this.SendPropertyChanged("ShoeBrand");
					this.OnShoeBrandChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShoeModel", DbType="NVarChar(50)")]
		public string ShoeModel
		{
			get
			{
				return this._ShoeModel;
			}
			set
			{
				if ((this._ShoeModel != value))
				{
					this.OnShoeModelChanging(value);
					this.SendPropertyChanging();
					this._ShoeModel = value;
					this.SendPropertyChanged("ShoeModel");
					this.OnShoeModelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShoePrice", DbType="Int")]
		public System.Nullable<int> ShoePrice
		{
			get
			{
				return this._ShoePrice;
			}
			set
			{
				if ((this._ShoePrice != value))
				{
					this.OnShoePriceChanging(value);
					this.SendPropertyChanging();
					this._ShoePrice = value;
					this.SendPropertyChanged("ShoePrice");
					this.OnShoePriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShoeQuentity", DbType="Int")]
		public System.Nullable<int> ShoeQuentity
		{
			get
			{
				return this._ShoeQuentity;
			}
			set
			{
				if ((this._ShoeQuentity != value))
				{
					this.OnShoeQuentityChanging(value);
					this.SendPropertyChanging();
					this._ShoeQuentity = value;
					this.SendPropertyChanged("ShoeQuentity");
					this.OnShoeQuentityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShoeInSale", DbType="Bit")]
		public System.Nullable<bool> ShoeInSale
		{
			get
			{
				return this._ShoeInSale;
			}
			set
			{
				if ((this._ShoeInSale != value))
				{
					this.OnShoeInSaleChanging(value);
					this.SendPropertyChanging();
					this._ShoeInSale = value;
					this.SendPropertyChanged("ShoeInSale");
					this.OnShoeInSaleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShoePicture", DbType="NVarChar(MAX)")]
		public string ShoePicture
		{
			get
			{
				return this._ShoePicture;
			}
			set
			{
				if ((this._ShoePicture != value))
				{
					this.OnShoePictureChanging(value);
					this.SendPropertyChanging();
					this._ShoePicture = value;
					this.SendPropertyChanged("ShoePicture");
					this.OnShoePictureChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SportClubs")]
	public partial class SportClub : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _ClubName;
		
		private EntitySet<SportEquipment> _SportEquipments;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnClubNameChanging(string value);
    partial void OnClubNameChanged();
    #endregion
		
		public SportClub()
		{
			this._SportEquipments = new EntitySet<SportEquipment>(new Action<SportEquipment>(this.attach_SportEquipments), new Action<SportEquipment>(this.detach_SportEquipments));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClubName", DbType="NVarChar(50)")]
		public string ClubName
		{
			get
			{
				return this._ClubName;
			}
			set
			{
				if ((this._ClubName != value))
				{
					this.OnClubNameChanging(value);
					this.SendPropertyChanging();
					this._ClubName = value;
					this.SendPropertyChanged("ClubName");
					this.OnClubNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SportClub_SportEquipment", Storage="_SportEquipments", ThisKey="Id", OtherKey="SportClubId")]
		public EntitySet<SportEquipment> SportEquipments
		{
			get
			{
				return this._SportEquipments;
			}
			set
			{
				this._SportEquipments.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_SportEquipments(SportEquipment entity)
		{
			this.SendPropertyChanging();
			entity.SportClub = this;
		}
		
		private void detach_SportEquipments(SportEquipment entity)
		{
			this.SendPropertyChanging();
			entity.SportClub = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Cloth")]
	public partial class Cloth : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _ClothType;
		
		private string _ClothGender;
		
		private string _ClothBrand;
		
		private string _ClothModel;
		
		private System.Nullable<int> _ClothPrice;
		
		private System.Nullable<int> _ClothQuentity;
		
		private System.Nullable<bool> _ClothIsShort;
		
		private System.Nullable<bool> _ClothIsDryFit;
		
		private string _ClothPicture;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnClothTypeChanging(string value);
    partial void OnClothTypeChanged();
    partial void OnClothGenderChanging(string value);
    partial void OnClothGenderChanged();
    partial void OnClothBrandChanging(string value);
    partial void OnClothBrandChanged();
    partial void OnClothModelChanging(string value);
    partial void OnClothModelChanged();
    partial void OnClothPriceChanging(System.Nullable<int> value);
    partial void OnClothPriceChanged();
    partial void OnClothQuentityChanging(System.Nullable<int> value);
    partial void OnClothQuentityChanged();
    partial void OnClothIsShortChanging(System.Nullable<bool> value);
    partial void OnClothIsShortChanged();
    partial void OnClothIsDryFitChanging(System.Nullable<bool> value);
    partial void OnClothIsDryFitChanged();
    partial void OnClothPictureChanging(string value);
    partial void OnClothPictureChanged();
    #endregion
		
		public Cloth()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClothType", DbType="NVarChar(50)")]
		public string ClothType
		{
			get
			{
				return this._ClothType;
			}
			set
			{
				if ((this._ClothType != value))
				{
					this.OnClothTypeChanging(value);
					this.SendPropertyChanging();
					this._ClothType = value;
					this.SendPropertyChanged("ClothType");
					this.OnClothTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClothGender", DbType="NVarChar(50)")]
		public string ClothGender
		{
			get
			{
				return this._ClothGender;
			}
			set
			{
				if ((this._ClothGender != value))
				{
					this.OnClothGenderChanging(value);
					this.SendPropertyChanging();
					this._ClothGender = value;
					this.SendPropertyChanged("ClothGender");
					this.OnClothGenderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClothBrand", DbType="NVarChar(50)")]
		public string ClothBrand
		{
			get
			{
				return this._ClothBrand;
			}
			set
			{
				if ((this._ClothBrand != value))
				{
					this.OnClothBrandChanging(value);
					this.SendPropertyChanging();
					this._ClothBrand = value;
					this.SendPropertyChanged("ClothBrand");
					this.OnClothBrandChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClothModel", DbType="NVarChar(50)")]
		public string ClothModel
		{
			get
			{
				return this._ClothModel;
			}
			set
			{
				if ((this._ClothModel != value))
				{
					this.OnClothModelChanging(value);
					this.SendPropertyChanging();
					this._ClothModel = value;
					this.SendPropertyChanged("ClothModel");
					this.OnClothModelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClothPrice", DbType="Int")]
		public System.Nullable<int> ClothPrice
		{
			get
			{
				return this._ClothPrice;
			}
			set
			{
				if ((this._ClothPrice != value))
				{
					this.OnClothPriceChanging(value);
					this.SendPropertyChanging();
					this._ClothPrice = value;
					this.SendPropertyChanged("ClothPrice");
					this.OnClothPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClothQuentity", DbType="Int")]
		public System.Nullable<int> ClothQuentity
		{
			get
			{
				return this._ClothQuentity;
			}
			set
			{
				if ((this._ClothQuentity != value))
				{
					this.OnClothQuentityChanging(value);
					this.SendPropertyChanging();
					this._ClothQuentity = value;
					this.SendPropertyChanged("ClothQuentity");
					this.OnClothQuentityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClothIsShort", DbType="Bit")]
		public System.Nullable<bool> ClothIsShort
		{
			get
			{
				return this._ClothIsShort;
			}
			set
			{
				if ((this._ClothIsShort != value))
				{
					this.OnClothIsShortChanging(value);
					this.SendPropertyChanging();
					this._ClothIsShort = value;
					this.SendPropertyChanged("ClothIsShort");
					this.OnClothIsShortChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClothIsDryFit", DbType="Bit")]
		public System.Nullable<bool> ClothIsDryFit
		{
			get
			{
				return this._ClothIsDryFit;
			}
			set
			{
				if ((this._ClothIsDryFit != value))
				{
					this.OnClothIsDryFitChanging(value);
					this.SendPropertyChanging();
					this._ClothIsDryFit = value;
					this.SendPropertyChanged("ClothIsDryFit");
					this.OnClothIsDryFitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClothPicture", DbType="NVarChar(MAX)")]
		public string ClothPicture
		{
			get
			{
				return this._ClothPicture;
			}
			set
			{
				if ((this._ClothPicture != value))
				{
					this.OnClothPictureChanging(value);
					this.SendPropertyChanging();
					this._ClothPicture = value;
					this.SendPropertyChanged("ClothPicture");
					this.OnClothPictureChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SportEquipment")]
	public partial class SportEquipment : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _SportType;
		
		private string _EquipmentName;
		
		private string _EquipmentCompany;
		
		private System.Nullable<int> _EquipmentPrice;
		
		private System.Nullable<int> _EquipmentQuentity;
		
		private System.Nullable<int> _SportClubId;
		
		private string _EquipmentPicture;
		
		private EntityRef<SportClub> _SportClub;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnSportTypeChanging(string value);
    partial void OnSportTypeChanged();
    partial void OnEquipmentNameChanging(string value);
    partial void OnEquipmentNameChanged();
    partial void OnEquipmentCompanyChanging(string value);
    partial void OnEquipmentCompanyChanged();
    partial void OnEquipmentPriceChanging(System.Nullable<int> value);
    partial void OnEquipmentPriceChanged();
    partial void OnEquipmentQuentityChanging(System.Nullable<int> value);
    partial void OnEquipmentQuentityChanged();
    partial void OnSportClubIdChanging(System.Nullable<int> value);
    partial void OnSportClubIdChanged();
    partial void OnEquipmentPictureChanging(string value);
    partial void OnEquipmentPictureChanged();
    #endregion
		
		public SportEquipment()
		{
			this._SportClub = default(EntityRef<SportClub>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SportType", DbType="NVarChar(50)")]
		public string SportType
		{
			get
			{
				return this._SportType;
			}
			set
			{
				if ((this._SportType != value))
				{
					this.OnSportTypeChanging(value);
					this.SendPropertyChanging();
					this._SportType = value;
					this.SendPropertyChanged("SportType");
					this.OnSportTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EquipmentName", DbType="NVarChar(50)")]
		public string EquipmentName
		{
			get
			{
				return this._EquipmentName;
			}
			set
			{
				if ((this._EquipmentName != value))
				{
					this.OnEquipmentNameChanging(value);
					this.SendPropertyChanging();
					this._EquipmentName = value;
					this.SendPropertyChanged("EquipmentName");
					this.OnEquipmentNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EquipmentCompany", DbType="NVarChar(50)")]
		public string EquipmentCompany
		{
			get
			{
				return this._EquipmentCompany;
			}
			set
			{
				if ((this._EquipmentCompany != value))
				{
					this.OnEquipmentCompanyChanging(value);
					this.SendPropertyChanging();
					this._EquipmentCompany = value;
					this.SendPropertyChanged("EquipmentCompany");
					this.OnEquipmentCompanyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EquipmentPrice", DbType="Int")]
		public System.Nullable<int> EquipmentPrice
		{
			get
			{
				return this._EquipmentPrice;
			}
			set
			{
				if ((this._EquipmentPrice != value))
				{
					this.OnEquipmentPriceChanging(value);
					this.SendPropertyChanging();
					this._EquipmentPrice = value;
					this.SendPropertyChanged("EquipmentPrice");
					this.OnEquipmentPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EquipmentQuentity", DbType="Int")]
		public System.Nullable<int> EquipmentQuentity
		{
			get
			{
				return this._EquipmentQuentity;
			}
			set
			{
				if ((this._EquipmentQuentity != value))
				{
					this.OnEquipmentQuentityChanging(value);
					this.SendPropertyChanging();
					this._EquipmentQuentity = value;
					this.SendPropertyChanged("EquipmentQuentity");
					this.OnEquipmentQuentityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SportClubId", DbType="Int")]
		public System.Nullable<int> SportClubId
		{
			get
			{
				return this._SportClubId;
			}
			set
			{
				if ((this._SportClubId != value))
				{
					if (this._SportClub.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnSportClubIdChanging(value);
					this.SendPropertyChanging();
					this._SportClubId = value;
					this.SendPropertyChanged("SportClubId");
					this.OnSportClubIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EquipmentPicture", DbType="NVarChar(MAX)")]
		public string EquipmentPicture
		{
			get
			{
				return this._EquipmentPicture;
			}
			set
			{
				if ((this._EquipmentPicture != value))
				{
					this.OnEquipmentPictureChanging(value);
					this.SendPropertyChanging();
					this._EquipmentPicture = value;
					this.SendPropertyChanged("EquipmentPicture");
					this.OnEquipmentPictureChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SportClub_SportEquipment", Storage="_SportClub", ThisKey="SportClubId", OtherKey="Id", IsForeignKey=true)]
		public SportClub SportClub
		{
			get
			{
				return this._SportClub.Entity;
			}
			set
			{
				SportClub previousValue = this._SportClub.Entity;
				if (((previousValue != value) 
							|| (this._SportClub.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._SportClub.Entity = null;
						previousValue.SportEquipments.Remove(this);
					}
					this._SportClub.Entity = value;
					if ((value != null))
					{
						value.SportEquipments.Add(this);
						this._SportClubId = value.Id;
					}
					else
					{
						this._SportClubId = default(Nullable<int>);
					}
					this.SendPropertyChanged("SportClub");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
